name: snapshare
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.15.2
  cloud_firestore: ^5.6.12
  firebase_auth: ^5.7.0
  firebase_storage: ^12.4.10
  flutter_svg: ^2.2.0
  image_picker: ^1.1.2
  provider: ^6.1.5
  uuid: ^4.5.1
  transparent_image: ^2.0.1
  flutter_staggered_grid_view: ^0.7.0
  timeago: ^3.7.1
  google_fonts: ^6.3.0
  firebase_messaging: ^15.2.10
  flutter_local_notifications: ^19.4.1
  http: ^1.5.0
  path_provider: ^2.1.5
  flutter_launcher_icons: ^0.14.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  change_app_package_name: ^1.5.0
  rename_app: ^1.6.5

flutter_launcher_icons:
  android: "launcher_icon"
  image_path: "assets/app_icon.png"

flutter:
  uses-material-design: true

  assets:
    - assets/
