// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC6YM0HM1_iMdaPTYYMKkqyc5dYil-S1ow',
    appId: '1:166349234009:web:9f75aa19343c23145ef648',
    messagingSenderId: '166349234009',
    projectId: 'instagram-6969',
    authDomain: 'instagram-6969.firebaseapp.com',
    storageBucket: 'instagram-6969.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBzEfV2w2iSnRhAtzrjsLIH0uItiX8n-H0',
    appId: '1:166349234009:android:45426a70b852ef665ef648',
    messagingSenderId: '166349234009',
    projectId: 'instagram-6969',
    storageBucket: 'instagram-6969.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC6YM0HM1_iMdaPTYYMKkqyc5dYil-S1ow',
    appId: '1:166349234009:web:7b95b672bf7eddd75ef648',
    messagingSenderId: '166349234009',
    projectId: 'instagram-6969',
    authDomain: 'instagram-6969.firebaseapp.com',
    storageBucket: 'instagram-6969.firebasestorage.app',
  );
}
